CREATE TABLE ACTORS (
	ACTOR_ID INT,
	ACTOR_NAME VARCHAR(50) ,
	CONSTRAINT ACTOR_ID PRIMARY KEY (ACTOR_ID));

CREATE TABLE ARTISTS (
	ARTIST_ID INT,
	ARTIST_NAME VARCHAR(50) ,
	CONSTRAINT ARTIST_ID PRIMARY KEY (ARTIST_ID));

CREATE TABLE CATEGORIES (
	CATEGORY_ID INT,
	CATEGORY_NAME VARCHAR(50) ,
	CATEGORY_TYPE VARCHAR(10) ,
	CONSTRAINT CATEGORY_ID PRIMARY KEY (CATEGORY_ID));

CREATE TABLE DIRECTORS (
	DIRECTOR_ID INT,
	DIRECTOR_NAME VARCHAR(50) ,
	CONSTRAINT DIRECTOR_ID PRIMARY KEY (DIRECTOR_ID));

CREATE TABLE MUSIC_TRACKS (
	TRACK_ID INT,
	RECORDING_ID INT,
	TRACK_TITLE VARCHAR(100) ,
	DURATION INT,
	CONSTRAINT TRACK_ID PRIMARY KEY (TRACK_ID));

CREATE TABLE MUSICS (
	RECORDING_ID INT,
	ARTIST_ID INT DEFAULT 0,
	ALBUM_TITLE VARCHAR(100) ,
	NUM_TRACKS INT,
	PRICE DOUBLE,
	STOCK_COUNT INT,
	CATEGORY_ID INT DEFAULT 0,
	CONSTRAINT MRECORDING_ID PRIMARY KEY (RECORDING_ID));

CREATE TABLE VIDEO_ACTORS (
	ROW_ID INT,
	ACTOR_ID INT,
	RECORDING_ID INT,
	CONSTRAINT ROW_ID PRIMARY KEY (ROW_ID));

CREATE TABLE VIDEOS (
	RECORDING_ID INT,
	VIDEO_TITLE VARCHAR(100) ,
	CATEGORY_ID INT DEFAULT 0,
	DURATION INT,
	RATING VARCHAR(2) ,
	PRICE DOUBLE,
	STOCK_COUNT INT,
	DIRECTOR_ID INT,
	YEAR_RELEASED INT,
	CONSTRAINT VRECORDING_ID PRIMARY KEY (RECORDING_ID));


ALTER TABLE MUSIC_TRACKS
	ADD CONSTRAINT MUSICS_TO_MUSIC_TRACKS
	FOREIGN KEY (RECORDING_ID) REFERENCES
		MUSICS (RECORDING_ID);
ALTER TABLE MUSICS
	ADD CONSTRAINT ARTISTS_TO_MUSICS
	FOREIGN KEY (ARTIST_ID) REFERENCES
		ARTISTS (ARTIST_ID);

ALTER TABLE MUSICS
	ADD CONSTRAINT CATEGORIES_TO_MUSICS 
	FOREIGN KEY (CATEGORY_ID) REFERENCES
		CATEGORIES (CATEGORY_ID);

ALTER TABLE VIDEO_ACTORS
	ADD CONSTRAINT ACTORS_TO_VIDEO_ACTORS
	FOREIGN KEY (ACTOR_ID) REFERENCES
		ACTORS (ACTOR_ID);

ALTER TABLE VIDEO_ACTORS
	ADD CONSTRAINT VIDEOS_TO_VIDEO_ACTORS
	FOREIGN KEY (RECORDING_ID) REFERENCES
		VIDEOS (RECORDING_ID);


ALTER TABLE VIDEOS
	ADD CONSTRAINT CATEGORIES_TO_VIDEOS
	FOREIGN KEY (CATEGORY_ID) REFERENCES
		CATEGORIES (CATEGORY_ID);

ALTER TABLE VIDEOS
	ADD CONSTRAINT DIRECTORS_TO_VIDEOS
	FOREIGN KEY (DIRECTOR_ID) REFERENCES
		DIRECTORS (DIRECTOR_ID);
