//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.12 at 10:48:31 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.scps.nyu.edu/jws/CarManagement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.nyu.scps.jws.carmanagement;
